                program membuat_biodata;
                uses crt;
                var
                nama,npm,alamat,ttl,nohp,motto:string;
                begin
                clrscr;
                writeln('Nama : ');
                readln(nama);
                writeln('NPM : ');
                readln(npm);
                writeln('Tempat, Tanggal, Lahir : ');
                readln(ttl);
                writeln('No Hp : ');
                readln(nohp);
                writeln('Motto : ');
                readln(motto);
                readkey
                end.